;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex30) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define PEOPLE 120)
(define PRICE 5.0)
(define PEOPLE-CHANGE 15)
(define PRICE-CHANGE 0.1)
(define PRICE-SENSITIVITY (/ PEOPLE-CHANGE PRICE-CHANGE))
(define FIXED 0)
(define PER-PERSON 1.5)
(define (attendees ticket-price)
  (- PEOPLE (* (- ticket-price PRICE)
               PRICE-SENSITIVITY)))
(define (revenue ticket-price)
  (* ticket-price (attendees ticket-price)))
(define (cost ticket-price)
  (+ FIXED (* PER-PERSON (attendees ticket-price))))
(define (profit ticket-price)
  (- (revenue ticket-price)
     (cost ticket-price)))

(profit 3)
(profit 4)
(profit 5)